---
title: denegny
email: denegny@gmail.com
description: 'Чуть позже напишу что-нибудь


'
baseurl:
url:
twitter_username: denegny
github_username: denegny
markdown: kramdown
theme: minima
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
